### ISSUE TITLE
Cannot import Kobalt project into IDEA

### ISSUE THREAD

**Issue by orangy** [cbeust/kobalt-intellij-plugin#55] opened 2016-08-03 13:45 UTC
2016-08-03 16:23:07,179 [  27548]   WARN - ution.rmi.RemoteProcessSupport - WARN: Cannot found Kobalt server port in /Users/orangy/.kobalt/kobaltServer.properties. The default port 1234 will be used. 
2016-08-03 16:23:08,189 [  28558]   WARN - ution.rmi.RemoteProcessSupport - WARN: Cannot found Kobalt server port in /Users/orangy/.kobalt/kobaltServer.properties. The default port 1234 will be used. 
2016-08-03 16:23:08,189 [  28558]   WARN - ution.rmi.RemoteProcessSupport - WARN: Cannot found Kobalt server port in /Users/orangy/.kobalt/kobaltServer.properties. The default port 1234 will be used. 
2016-08-03 16:23:09,195 [  29564]   WARN - ution.rmi.RemoteProcessSupport - WARN:      Server failed to start after 7 attempts 
2016-08-03 16:23:09,195 [  29564]   WARN - ution.rmi.RemoteProcessSupport - WARN: Cannot found Kobalt server port in /Users/orangy/.kobalt/kobaltServer.properties. The default port 1234 will be used. 
2016-08-03 16:23:09,213 [  29582]   WARN - ution.rmi.RemoteProcessSupport - WARN: WebSocket failure: Failed to connect to localhost/0:0:0:0:0:0:0:1:1234 response message: null response code: null 
2016-08-03 16:23:09,225 [  29594]   WARN - nal.AbstractExternalSystemTask - java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:1234
Failed to connect to localhost/0:0:0:0:0:0:0:1:1234 
com.intellij.openapi.externalSystem.model.ExternalSystemException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:1234
Failed to connect to localhost/0:0:0:0:0:0:0:1:1234
    at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:59)
    at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:415)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4.run(ExternalSystemUtil.java:485)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
    at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:561)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
java.lang.reflect.UndeclaredThrowableException
    at com.sun.proxy.$Proxy3.resolveProjectInfo(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
    at sun.rmi.transport.Transport$1.run(Transport.java:200)
    at sun.rmi.transport.Transport$1.run(Transport.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
    at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
    at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
    at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
    at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
    at com.sun.proxy.$Proxy117.resolveProjectInfo(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.execution.rmi.RemoteUtil.invokeRemote(RemoteUtil.java:169)
    at com.intellij.execution.rmi.RemoteUtil.access$300(RemoteUtil.java:36)
    at com.intellij.execution.rmi.RemoteUtil$2$1$1.compute(RemoteUtil.java:150)
    at com.intellij.execution.rmi.RemoteUtil.executeWithClassLoader(RemoteUtil.java:226)
    at com.intellij.execution.rmi.RemoteUtil$2$1.invoke(RemoteUtil.java:147)
    at com.sun.proxy.$Proxy117.resolveProjectInfo(Unknown Source)
    at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
    at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:415)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4.run(ExternalSystemUtil.java:485)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
    at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:561)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.openapi.externalSystem.service.RemoteExternalSystemFacadeImpl$1.invoke(RemoteExternalSystemFacadeImpl.java:113)
    at com.sun.proxy.$Proxy3.resolveProjectInfo(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
    at sun.rmi.transport.Transport$1.run(Transport.java:200)
    at sun.rmi.transport.Transport$1.run(Transport.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
    ... 3 more
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:1234
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
    at com.beust.kobalt.intellij.resolver.DependenciesProcessor.sendGetDependenciesWebSocket(DependenciesProcessor.kt:85)
    at com.beust.kobalt.intellij.resolver.DependenciesProcessor.resolveDependencies(DependenciesProcessor.kt:37)
    at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.doResolveProjectInfo(KobaltProjectResolver.kt:47)
    at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.resolveProjectInfo(KobaltProjectResolver.kt:38)
    at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.resolveProjectInfo(KobaltProjectResolver.kt:26)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.a(RemoteExternalSystemProjectResolverImpl.java:37)
    at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
    ... 23 more
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:1234
    at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:142)
    at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
    at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
    at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
    at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
    at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
    at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
    at okhttp3.RealCall.getResponse(RealCall.java:240)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
    at okhttp3.RealCall.access$100(RealCall.java:30)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    ... 3 more

2016-08-03 16:23:09,227 [  29596]   WARN - ctExternalProjectImportBuilder - java.lang.reflect.UndeclaredThrowableException
    at com.sun.proxy.$Proxy3.resolveProjectInfo(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
    at sun.rmi.transport.Transport$1.run(Transport.java:200)
    at sun.rmi.transport.Transport$1.run(Transport.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
    at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
    at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
    at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
    at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
    at com.sun.proxy.$Proxy117.resolveProjectInfo(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.execution.rmi.RemoteUtil.invokeRemote(RemoteUtil.java:169)
    at com.intellij.execution.rmi.RemoteUtil.access$300(RemoteUtil.java:36)
    at com.intellij.execution.rmi.RemoteUtil$2$1$1.compute(RemoteUtil.java:150)
    at com.intellij.execution.rmi.RemoteUtil.executeWithClassLoader(RemoteUtil.java:226)
    at com.intellij.execution.rmi.RemoteUtil$2$1.invoke(RemoteUtil.java:147)
    at com.sun.proxy.$Proxy117.resolveProjectInfo(Unknown Source)
    at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
    at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:415)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4.run(ExternalSystemUtil.java:485)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
    at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:561)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.openapi.externalSystem.service.RemoteExternalSystemFacadeImpl$1.invoke(RemoteExternalSystemFacadeImpl.java:113)
    at com.sun.proxy.$Proxy3.resolveProjectInfo(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
    at sun.rmi.transport.Transport$1.run(Transport.java:200)
    at sun.rmi.transport.Transport$1.run(Transport.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
    ... 3 more
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:1234
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
    at com.beust.kobalt.intellij.resolver.DependenciesProcessor.sendGetDependenciesWebSocket(DependenciesProcessor.kt:85)
    at com.beust.kobalt.intellij.resolver.DependenciesProcessor.resolveDependencies(DependenciesProcessor.kt:37)
    at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.doResolveProjectInfo(KobaltProjectResolver.kt:47)
    at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.resolveProjectInfo(KobaltProjectResolver.kt:38)
    at com.beust.kobalt.intellij.resolver.KobaltProjectResolver.resolveProjectInfo(KobaltProjectResolver.kt:26)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.a(RemoteExternalSystemProjectResolverImpl.java:37)
    at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
    ... 23 more
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:1234
    at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:142)
    at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
    at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
    at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
    at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
    at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
    at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
    at okhttp3.RealCall.getResponse(RealCall.java:240)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
    at okhttp3.RealCall.access$100(RealCall.java:30)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    ... 3 more

**Comment by orangy** [comment] 2016-08-03 16:58
Note, that it seems server is started ok on refresh, but doesn’t start for some reason on import.

**Comment by cbeust** [comment] 2016-08-03 17:06
@dmitry-zhuravlev 

@orangy is working on Ktor and he's trying to import the Kobalt build I created for this project, which you can download from my fork:

https://github.com/cbeust/ktor

and switch to the `kobalt` branch.

**Comment by dmitry-zhuravlev** [comment] 2016-08-03 19:17
Looks like an old problem with invalid root tag in Kobalt settings... @orangy can you recheck please if the root tag is 'kobaltSettings' and not 'kobalt-settings'

**Comment by orangy** [comment] 2016-08-03 22:46
When the problem was there, settings.xml didn't exist. Actually, now when I created it, import works fine. So probably missing file causes it.

**Comment by orangy** [comment] 2016-08-03 22:52
Wrote too fast, it failed later. Starting server from command line with `kobaltw --server  —force` works and allows project import just fine.

**Comment by cbeust** [comment] 2016-08-03 22:54
So it looks like there is still a bug and the plug-in sometimes is not able to successfully launch the server. It would be nice to find why since it's an important first impression for new users.

@dmitry-zhuravlev: @orangy suggested it might only happen when you import the project but not when you synchronize your build file, does this help?

**Comment by dmitry-zhuravlev** [comment] 2016-08-04 10:44
I tried the following (latest Kobalt plugin from repository and Kobalt 0.885):
1) checkout from Version Control -> Git
2) open project with IDEA 
3) checkout new local branch from remote one "kobalt"
4) reopen the project for triggering notification about detached Kobalt project (I know it is not so convenient and should be improved)
5) then click "import Kobalt project" and proceed with default settings:
![importing](https://cloud.githubusercontent.com/assets/6297697/17398752/0280d6b8-5a47-11e6-8402-809aea54506a.PNG)
![imported](https://cloud.githubusercontent.com/assets/6297697/17398755/07269040-5a47-11e6-8da1-e5ee8bda6c25.PNG)
![toolwindow](https://cloud.githubusercontent.com/assets/6297697/17398757/0a88a2f0-5a47-11e6-90de-2a134e9a356b.PNG)

Also I seen some other small problem like `kobalt.jar` library in `Build.kt` module doesn't properly resolved and resolved only after project reopen.

But I didn't get the mentioned `Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:1234`

**Comment by cbeust** [comment] 2016-08-04 12:22
@orangy Are you seeing the same thing as @dmitry-zhuravlev is?

If yes, then the only issue left is that the `Build.kt` module only gets `kobalt.jar` in its classpath after a reopen, any idea why, @dmitry-zhuravlev ?

**Comment by orangy** [comment] 2016-08-04 12:26
No, this is not what I'm seeing. After import configuration dialog I just see ConnectException message box and it gets back to Import Configuration. If I start server manually, it works more or less like @dmitry-zhuravlev explains.

**Comment by cbeust** [comment] 2016-08-04 12:28
Ok so the server is still not being started correctly for @orangy.

@dmitry-zhuravlev, can you add some logging to the plug-in so we can investigate what's going on, since neither you nor I can reproduce the problem?

**Comment by dmitry-zhuravlev** [comment] 2016-08-04 12:54
Hm... At the moment I'm not sure if the logging could help. The exception log is obvious in this case: `Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:1234` 
So the server shutdown for some reason.

For me it is a quite strange to see this warnings:
`WARN - ution.rmi.RemoteProcessSupport - WARN: Cannot found Kobalt server port in /Users/orangy/.kobalt/kobaltServer.properties. The default port 1234 will be used.`
As far as I know Kobalt should create this properties.

Lets try to synchronize our config files:
[conf.zip](https://github.com/cbeust/kobalt-intellij-plugin/files/401642/conf.zip)

@orangy 
Please shutdown any Kobalt server instances on your machine 
and try to put kobaltServer.properties to the 
`/Users/orangy/.kobalt/kobaltServer.properties`
and settings.xml to the
`/Users/orangy/.config/kobalt/settings.xml`

Also adjust `local-repo` in settings.xml if needed.

**Comment by cbeust** [comment] 2016-08-06 00:10
@dmitry-zhuravlev I think the plug-in needs to track whether the server started properly or not, and if not, display the error.

I just came across a situation where the `kobalt.jar` was corrupted and so the server couldn't start, but all the plug-in told me is that it couldn't connect to the server. It would be nice if the plug-in could display something like "Couldn't start the server because... " followed by the output of the server launch.

**Comment by dmitry-zhuravlev** [comment] 2016-08-06 07:48
But how to display the arbitrary error? If the server doesn't start it couldn't "tell" to the plugin about error which prevent from successful startup.

**Comment by dmitry-zhuravlev** [comment] 2016-08-06 07:50
Maybe somehow to get the error from output of the process... I'll recheck how to do it.

**Comment by cbeust** [comment] 2016-08-06 14:32
Yes, capturing the output of the process is what I was referring to.

## 

Cédric

**Comment by dmitry-zhuravlev** [comment] 2017-03-29 15:56
Retested Ktor project on the latest version of Kobalt and IDEA plugin and it works for me. So I'm closing the issue.

**Closed as completed by dmitry-zhuravlev** 2017-03-29 15:56 UTC
