### ISSUE TITLE
Can't import a Kobalt project into IntelliJ

### ISSUE THREAD

**Issue by sargunv** [cbeust/kobalt-intellij-plugin#33] opened 2016-05-28 16:45 UTC
I'm getting this error when trying to import a freshly cloned project: 
`com.intellij.execution.configurations.SimpleJavaParameters.toCommandLine()Lcom/intellij/execution/configurations/GeneralCommandLine;`

Steps to reproduce
- Clone a repo (I tried with https://github.com/pokesource/PokeKotlin)
- Launch IntelliJ
- Try to import the project

**Comment by cbeust** [comment] 2016-05-28 18:11
I just saw this error as well but I wasn't able to repeat it after that (tried with both the binary plug-in and the development one as well).

**Comment by sargunv** [comment] 2016-05-28 18:13
I'm getting the error every time, with the latest version of IntelliJ and the plugin.

**Comment by sargunv** [comment] 2016-05-28 18:15
Here's a log if that helps: http://pastebin.com/raw/QCTsmjXE

**Comment by cbeust** [comment] 2016-05-29 00:13
I deployed a new version which seems to fix the problem for me, even though I'm not sure I did anything.

That new version displays a different error but it seems to sync fine at least, I'll file a separate issue for it.

@sargunster Can you update and report back?

**Comment by sargunv** [comment] 2016-05-29 00:19
Yep, seems to work now. Thanks!

**Comment by sargunv** [comment] 2016-05-29 00:20
BTW, this also fixed #32

**Comment by sargunv** [comment] 2016-05-30 19:13
This problem is happening again ):

**Comment by DevCharly** [comment] 2016-05-31 22:55
@dmitry-zhuravlev it seems that you have not checked in the packages `com.beust.kobalt.intellij.model.data` and `com.beust.kobalt.intellij.project.view`. They are in your JAR, but not in git

**Comment by dmitry-zhuravlev** [comment] 2016-06-01 06:40
@devcharly: Classes mentioned by you shouldn't checked in git. It was some investigation from my side and shouldn't affect the work of the plugin. I'll remove it and recheck once again.

**Comment by dmitry-zhuravlev** [comment] 2016-06-01 10:35
Here is my build without this classes.
[kobalt-intellij-plugin.zip](https://github.com/cbeust/kobalt-intellij-plugin/files/293172/kobalt-intellij-plugin.zip)

The mentioned problem wasn't reproduced with this distribution of plugin.

After looking in log http://pastebin.com/raw/QCTsmjXE I found that java.lang.NoSuchMethodError caused by plugin SDK mismatch. 

@cbeust try to build plugin with exactly IDEA:
IntelliJ IDEA 2016.1.2
Build #IU-145.972, built on May 14, 2016

This should resolve this problem.

**Comment by DevCharly** [comment] 2016-06-01 12:19
Hm, but shouldn't fail the compiler if Cedric's IntelliJ does not have that method?

BTW if this plug-in depends on IDEA 2016.1, then `<idea-version since-build="131"/>` in `plugin.xml` should be changed to 145 too avoid that users can install it in IDEA 15 or older.

**Comment by DevCharly** [comment] 2016-06-01 13:00
Had a look at the byte code of both versions.

Cedric's version directly calls into IDEA API `com.intellij.execution.configurations.SimpleJavaParameters.toCommandLine()`

Dmitry's version on the other hand invokes `ServerUtil$Companion.toCommandLine`

Can the used Kotlin compiler version have any effect?

<img width="816" alt="2016-06-01_14-43-49" src="https://cloud.githubusercontent.com/assets/5604048/15710066/978629c8-2808-11e6-9508-61f148deecaf.png">

**Comment by dmitry-zhuravlev** [comment] 2016-06-01 17:00
@DevCharly Good point!
Now it is clear for me what happens:
It seems that @cbeust compiles against EAP builds. In EAP there is SimpleJavaParameters.toCommandLine() method. But I also have an extension toCommandLine() in ServerUtil class. Methods defined in class always wins (have priority over extensions) thats why plugin compiled with EAP version uses SimpleJavaParameters.toCommandLine() but it breaks backward compatible with current IDEA release version where is no SimpleJavaParameters.toCommandLine() method.

**Comment by cbeust** [comment] 2016-06-01 17:02
@dmitry-zhuravlev Good catch.

What do you recommend I should do? I'm currently building (and shipping) against:

![image](https://cloud.githubusercontent.com/assets/92322/15718372/860d0b8e-27d7-11e6-81bd-eac09e91ad29.png)

**Comment by dmitry-zhuravlev** [comment] 2016-06-01 17:08
The most recent version is:
![screen shot 2016-06-01 at 20 04 27](https://cloud.githubusercontent.com/assets/6297697/15718495/aad6087a-283c-11e6-8f3e-b60e21afdd2b.png)

Maybe you already have 145.972 but with old name 145.597.3 because name of the JDK never updated even if the IDEA distribution updated.

Just make sure that you have most recent release update of IDEA.

**Comment by cbeust** [comment] 2016-06-01 17:10
I believe I'm using the latest:

![image](https://cloud.githubusercontent.com/assets/92322/15718591/a4b30bc8-27d8-11e6-8a7c-017164095aa6.png)

**Comment by dmitry-zhuravlev** [comment] 2016-06-01 17:10
Not EAP, should be the release...

**Comment by dmitry-zhuravlev** [comment] 2016-06-01 17:11
IntelliJ IDEA 2016.1.2
Build #IU-145.972, built on May 14, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by cbeust** [comment] 2016-06-01 17:16
Got it. I installed:

![image](https://cloud.githubusercontent.com/assets/92322/15718798/8f5b3682-27d9-11e6-87a7-51942a2c70e2.png)

and I'll be using that one to develop and package the plug-in from now on.

**Comment by cbeust** [comment] 2016-06-01 17:23
I just deployed 1.110 with the release version, which should fix the `toCommandLine()` errors that have been reported. Please try and report back.

/cc @pabl0rg

**Comment by pabl0rg** [comment] 2016-06-02 09:45
I am no longer getting the toCommandLine() error with the latest plugin

**Closed as completed** 2016-06-02 11:36 UTC
