### ISSUE TITLE
Kobalt tasks showing up multiple times in IDE

### ISSUE THREAD

**Issue by dittert** [cbeust/kobalt-intellij-plugin#71] opened 2017-03-25 09:40 UTC
This bug was filed against 1.0.23.

![duplicate tasks](https://cloud.githubusercontent.com/assets/1113632/24321192/f4fa5ab6-1146-11e7-9424-b3d5addf1d5f.png)

Content of ```Build.kt```:

```
import com.beust.kobalt.buildScript
import com.beust.kobalt.plugin.application.application
import com.beust.kobalt.plugin.packaging.assemble
import com.beust.kobalt.project

val bs = buildScript {
    repos()
}


val p = project {

    name = "kobalt-example"
    group = "com.example"
    artifactId = name
    version = "0.1"

    sourceDirectories {
        path("src/main/kotlin")
    }

    sourceDirectoriesTest {
        path("src/test/kotlin")
    }

    dependencies {
        compile("org.jetbrains.kotlin:kotlin-stdlib:1.1.1")
    }

    dependenciesTest {
        compile("junit:junit:4.12")
    }

    assemble {
        jar {
        }
    }

    application {
        mainClass = "com.example.MainKt"
    }
}
```

These duplicates seem to be triggered by project refreshes. It doesn't happen all the time, though. I have seen the following:

- IDEA opens the project => tasks are correct
- IDEA executes a project refresh through Kobalt => duplicate tasks appear

It doesn't always stay at two. I have also seen three identical tasks.

**Comment by dmitry-zhuravlev** [comment] 2017-03-25 09:43
Can confirm this.  Also see this problem. Seems like some regression inside IDEA external API.

**Comment by cbeust** [comment] 2017-03-25 14:17
@dmitry-zhuravlev Is the Kobalt server sending you these dependencies duplicated or is it an IDEA regression?

**Comment by dmitry-zhuravlev** [comment] 2017-03-29 12:28
@cbeust It seems that Kobalt server for some reason sends duplicate tasks:
![image](https://cloud.githubusercontent.com/assets/6297697/24454311/0e578704-1494-11e7-95de-aacb9213003b.png)

I can filter it within plugin, but I think this should be fixed primarily on Kobalt side.

**Comment by cbeust** [comment] 2017-03-29 14:07
Definitely looks like a bug on Kobalt side, will take a look.

-- 
Cédric

**Comment by cbeust** [comment] 2017-03-30 21:54
I just took a look on the server side and I'm not seeing any duplication:

![image](https://cloud.githubusercontent.com/assets/92322/24527800/b176635a-1558-11e7-9e36-d6aad023588d.png)

How can I reproduce this?

**Comment by dmitry-zhuravlev** [comment] 2017-03-31 05:28
You should revert my commit first https://github.com/dmitry-zhuravlev/kobalt-intellij-plugin/commit/81defd2b21bd98fbc0e45a5808a3a9c0b5a80012

**Comment by cbeust** [comment] 2017-03-31 06:29
I'm showing the server side.

**Comment by pabl0rg** [comment] 2017-03-31 08:04
I also have this problem (kobalt 1.0.41, plugin 1.123, IJ 2016.3)

**Comment by dmitry-zhuravlev** [comment] 2017-03-31 14:10
> I'm showing the server side.

Very strange... maybe it is some serialization/deserialization issue. Anyway the problem will be solved by using Set instead of List on both sides.

**Comment by dmitry-zhuravlev** [comment] 2017-04-06 15:29
Duplicates should be filtered by using `Set` collection.

**Closed as completed by dmitry-zhuravlev** 2017-04-06 15:29 UTC
